<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\..\..\packages\hosting\AgenticLogAnalyzer.Hosting\AgenticLogAnalyzer.Hosting.csproj" />
    <ProjectReference Include="..\..\..\packages\infrastructure\AgenticLogAnalyzer.Infrastructure\AgenticLogAnalyzer.Infrastructure.csproj" />
  </ItemGroup>
</Project>
